services:
    hrm-backend:
        build:
            context: .
            dockerfile: Dockerfile.local
        volumes:
            - ./src:/usr/src/app/src
            - ./package.json:/usr/src/app/package.json
            - ./package-lock.json:/usr/src/app/package-lock.json
            - app_uploads:/usr/src/app/uploads
        ports:
            - '3000:3000'
        environment:
            - NODE_ENV=development
            - POSTGRES_HOST=postgres
            - POSTGRES_PORT=5432
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=only-hrm
            - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/only-hrm?schema=public
        networks:
            - internal
        depends_on:
            - postgres
            - redis
            - strapi
        restart: unless-stopped
    postgres:
        image: postgres:latest
        ports:
            - '6500:5432'
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=only-hrm
        volumes:
            - pg_data:/var/lib/postgresql/data
            - ./src/database/init:/docker-entrypoint-initdb.d
        networks:
            - internal
        restart: unless-stopped
    redis:
        image: redis:latest
        ports:
            - '6379:6379'
        volumes:
            - redis_data:/data
        networks:
            - internal
        restart: unless-stopped
        command: redis-server --appendonly yes
    strapi:
        image: strapi/strapi:latest
        environment:
            - DATABASE_CLIENT=postgres
            - DATABASE_HOST=postgres
            - DATABASE_PORT=5432
            - DATABASE_NAME=only-hrm
            - DATABASE_USERNAME=postgres
            - DATABASE_PASSWORD=postgres
            - DATABASE_SSL=false
        volumes:
            - strapi_data:/srv/app
        ports:
            - '1337:1337'
        networks:
            - internal
        depends_on:
            - postgres
        restart: unless-stopped

networks:
    internal:
        driver: bridge

volumes:
    pg_data:
    app_uploads:
    pgadmin_data:
    redis_data:
    strapi_data:
