import { EditableFields } from '.';

export const MIN_PASSWORD_LENGTH = 8;

export const EDITABLE_FIELDS: EditableFields = {
    EMPLOYEE: ['avatar', 'dateBirth'],
    ADMIN_DEPARTMENT: [
        'email',
        'phone',
        'telegram',
        'name',
        'surname',
        'post',
        'grade',
        'patronymic',
        'education',
        'courses',
        'timeZone',
        'role',
        'avatar',
        'dateBirth',
    ],
    ADMIN: [
        'dateStart',
        'departmentId',
        'email',
        'phone',
        'telegram',
        'name',
        'surname',
        'post',
        'grade',
        'patronymic',
        'education',
        'courses',
        'timeZone',
        'role',
        'avatar',
        'dateBirth',
    ],
    CEO: [
        'dateStart',
        'departmentId',
        'email',
        'phone',
        'telegram',
        'name',
        'surname',
        'post',
        'grade',
        'patronymic',
        'education',
        'courses',
        'timeZone',
        'role',
        'avatar',
        'dateBirth',
    ],
};
